// GENERATED BY npm build
// DO NOT MODIFY

#define ID_ASSET_0 350
#define ID_ASSET_1 351
#define ID_ASSET_2 352
#define ID_ASSET_3 353
#define ID_ASSET_4 354
#define ID_ASSET_5 355
#define ID_ASSET_6 356
#define ID_ASSET_7 357
#define ID_ASSET_8 358
#define ID_ASSET_9 359
